### ISSUE TITLE
Why use the next operator here?

### ISSUE THREAD

**Issue by lassebenni** [schubergphilis/wiki-challenge#1]
Hi @costastf , thanks for the awesome repo. I have a question: what is the advantage of using the next operator here instead of just the list comprehension?

https://github.com/schubergphilis/wiki-challenge/blob/7f106a20f90c1da1b2c7b5c4478a00550b25e7cf/wikiseries.py#L67

**Comment by costastf** [comment]
Because it is not a list comprehension, it is a generator comprehension, so it does not calculate anything, it just returns the generator. next kicks the generator off and gets it's first value. Makes sense?

**Comment by lassebenni** [comment]
Makes sense now, thanks!
